### ISSUE TITLE
05-22-2024

### ISSUE THREAD

**Issue by huizezhang-sherry** [Knicey/stglyphs#2]
- [x]  start on a package structure: DESCRIPTION file, R folder for code, license, data-raw and data folder, readme.md/rmd. If possible, pkgdown site, setup GitHub workflow

- [x] pull down data from NOAA - GHCN-Daily, 4/5 stations in region of your choice, 3-5 years (the script in the data-raw folder, the actual data go to the data folder) - look at climate.R file in the cubble package as an example

- [x] make a segment plot on the data to look at seasonal differences across locations

**Comment by dicook** [comment]
The reason for the segment plot is to explore seasonal trends and variability.

**Comment by Knicey** [comment]
All completed or transfered to #3
